apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: minio-gateway
  namespace: minio-tenant
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https-minio-api
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: simplefbo-cf-tls
      minProtocolVersion: TLSV1_2
      cipherSuites:
      - ECDHE-RSA-AES256-GCM-SHA384
      - ECDHE-RSA-AES128-GCM-SHA256
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: minio-api-vs
  namespace: minio-tenant
spec:
  hosts:
  - "minio.dbslone.com"
  gateways:
  - minio-gateway
  http:
  - route:
    - destination:
        host: minio
        port:
          number: 443