{{- if .Values.replicasetPruner.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "gateway-helm.fullname" . }}-replicaset-pruner
  labels:
    {{- include "gateway-helm.labels" . | nindent 4 }}
rules:
- apiGroups: ["apps"]
  resources: ["replicasets", "deployments"]
  verbs: ["get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "gateway-helm.fullname" . }}-replicaset-pruner
  labels:
    {{- include "gateway-helm.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "gateway-helm.fullname" . }}-replicaset-pruner
subjects:
- kind: ServiceAccount
  name: {{ include "gateway-helm.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}

